services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: -secret-pw-
      MYSQL_DATABASE: financemanager
    ports:
      - "3306:3306"
    networks:
      - mariadb_network
    volumes:
      - ./data:/data/db

networks:
  mariadb_network:
    driver: bridge